### ISSUE TITLE
Not able to migrate my project to null safety due to "The getter 'library' was called on null" error in database.dart

### ISSUE THREAD

**Issue by novas1r1** [simolus3/drift#1767]
Hello,
today I tried to upgrade my flutter project to null safety. I cleaned everything up, moved from moor to drift (which worked perfectly fine, great job!) and ran "dart migrate". I'm getting the following error:

```
Exception details:

NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library at offset 625 in C:\Development\leomedia\leoTicketScan\lib\core\database\database.dart (IntColumn)

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      Variables._createDecoratedElementType (package:nnbd_migration/src/variables.dart:375:40)
#2      Variables.decoratedElementType (package:nnbd_migration/src/variables.dart:97:9)
#3      EdgeBuilder.visitNamedType (package:nnbd_migration/src/edge_builder.dart:1430:41)
#4      NamedTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:7579:50)
#5      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#6      EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2604:5)
#7      EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1334:5)
#8      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7177:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#10     EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2330:7)
#11     EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:681:7)
#12     EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:648:5)
#13     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1494:50)
#14     EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2312:24)
#15     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1508:9)
#16     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#17     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#18     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#19     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#21     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:231:12)
#22     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:164:16)
#23     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1093:20)
#24     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1091:28)
#25     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1025:26)
<asynchronous suspension>
#26     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1091:5)
<asynchronous suspension>
#27     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:698:24)
<asynchronous suspension>
#28     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#29     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#30     DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:18)
<asynchronous suspension>
#31     runDartdev (package:dartdev/dartdev.dart:67:16)
<asynchronous suspension>
#32     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

Here's the first part of my `database.dart`:
```
class TestEvents extends Table {
  IntColumn get id => integer()();
  TextColumn get uuid => text()();
  TextColumn get title => text()();
  TextColumn get subtitle => text().nullable()();
  DateTimeColumn get begin => dateTime().nullable()();
  BoolColumn get isSynchronized =>
      boolean().withDefault(const Constant(false))();
  DateTimeColumn get ticketFetchTime => dateTime().nullable()();
  IntColumn get ticketCount => integer().withDefault(const Constant(0))();

  @override
  Set<Column> get primaryKey => {id};
}
```
Here's my doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.17763.2686], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 4.2)
[√] Android Studio
[√] VS Code (version 1.65.2)
[√] Connected device (2 available)
[√] HTTP Host Availability
```

I found someone having a similar problem with migration which was because of typedefs. Since "IntColumn" is a typedef - could this be the problem?

Can I somehow work around this? I'm really stuck here.

Best regards and thanks in advance!
Verena

**Comment by simolus3** [comment]
Unfortunately I don't think there's much that I can do about this. I'm not aware of this problem, but it appears to be a bug in Dart's migration tooling. I'll have to redirect you to the [Dart SDK](https://github.com/dart-lang/sdk/) where the migration logic for Dart is hosted, maybe open an issue there?

To work around this problem, you could try migrating that file manually and then use the migration tooling for all other files.  So essentially:

1. Add a `//@dart=2.12` comment on the top of `database.dart` to opt that file into null-safety
2. Fix compile errors in table definitions
3. Re-run `flutter pub run build_runner build` so that the generated `database.g.dart` part file is also opted into null-safety
4. Fix other compile errors in `database.dart`
5. Now run `dart migrate` again, it shouldn't try to compute fixes for the database file.

I'll close this issue since it's likely to not be drift's fault (the migration tooling shouldn't crash for valid Dart code), but I'm happy to share more tips on the migration if that doesn't work.

**Comment by novas1r1** [comment]
Hey @simolus3,
thanks for the super fast response! 
I managed to work around it by commenting out the database.dart. I didn't know about the opt-out until now - so thanks for that hint.
