### ISSUE TITLE
[DoUpdate.withExcluded] Type incompatibility ((Table, Table) => Where)?

### ISSUE THREAD

**Issue by Holofox** [simolus3/drift#1781]
Hello! I need to update a value in a table if the new one is equal or greater than the old one. 

I am using the following implementation:

```dart
Future<void> renewLabels(List<MlImageLabel> data) async {
  return batch(
    (batch) => batch.insertAll<ScanObjectTable, ScanObjectData>(
      scanObjectTable,
      data.map(
        (o) => ScanObjectTableCompanion(
          name: Value(o.name),
          confidence: Value(o.confidence),
        ),
      ),
      onConflict: DoUpdate.withExcluded(
        (old, excluded) => ScanObjectTableCompanion.custom(
          name: old.name.dartCast(),
          confidence: excluded.confidence.dartCast(),
        ),
        where: (old, excluded) =>
            excluded.confidence.isBiggerOrEqual(old.confidence),
      ),
    ),
  );
}
```

Or:

```dart
Future<void> renewLabels(List<MlImageLabel> data) async {
  return batch((b) {
    for (final d in data) {
      b.insert<ScanObjectTable, ScanObjectData>(
        scanObjectTable,
        ScanObjectTableCompanion(
          name: Value(d.name),
          confidence: Value(d.confidence),
        ),
        onConflict: DoUpdate.withExcluded(
              (old, excluded) => ScanObjectTableCompanion.custom(
            name: old.name.dartCast(),
            confidence: excluded.confidence.dartCast(),
          ),
          where: (old, excluded) =>
              excluded.confidence.isBiggerOrEqual(old.confidence),
        ),
      );
    }
  });
}
```

But I am getting the following error:

```console
E/flutter (20044): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '(ScanObjectTable, ScanObjectTable) => Where' is not a subtype of type '((Table, Table) => Where)?'
E/flutter (20044): #0      InsertStatement.createContext.writeDoUpdate (package:drift/src/runtime/query_builder/statements/insert.dart:222:24)
E/flutter (20044): #1      InsertStatement.createContext (package:drift/src/runtime/query_builder/statements/insert.dart:232:7)
E/flutter (20044): #2      Batch.insert (package:drift/src/runtime/api/batch.dart:52:10)
E/flutter (20044): #3      Batch.insertAll (package:drift/src/runtime/api/batch.dart:72:7)
E/flutter (20044): #4      MlRepository.renewLabels.<anonymous closure> (package:promo/src/internal/infra/db/repositories/ml_repository.dart:24:24)
E/flutter (20044): #5      DatabaseConnectionUser.batch (package:drift/src/runtime/api/connection_user.dart:505:30)
````

Why is this happening and what am I doing wrong?

You can rewrite it like this, then an exception will not be thrown:

```dart
Future<void> renewLabels(List<MlImageLabel> data) async {
  for (final label in data) {
    await db.into(scanObjectTable).insert(
          ScanObjectTableCompanion(
            name: Value(label.name),
            confidence: Value(label.confidence),
          ),
          onConflict: DoUpdate.withExcluded(
            (old, excluded) => ScanObjectTableCompanion.custom(
              name: old.name.dartCast(),
              confidence: excluded.confidence.dartCast(),
            ),
            where: (old, excluded) =>
                excluded.confidence.isBiggerOrEqual(old.confidence),
          ),
        );
  }
}
```

**Comment by simolus3** [comment]
Nice catch, what a nasty typo. I've fixed this in 221ca2382ffe377586d452b52025e0498a3d6696.
