### ISSUE TITLE
.watch() and .map() function doesn't work on joined tables/custom data class

### ISSUE THREAD

**Issue by adummy832** [simolus3/drift#1785]
Hello again :)
I have this very simple app that contains 3 tables, I'm also following the documentation
on writing basic `"joins"` and rendering it to the screen. Just wanted to ask why my UI doesn't 
rebuild even though I manage to create data on every button press. I'm using Streams on the db query
and a simple StreamBuilder at the UI. Really don't have a clue what I'm missing here. Asking for your
assistance on this and I also provided simple snippet of my code. Thanks! :)

### DB
```dart
@DataClassName("Category")
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  IntColumn get parentId => integer()
      .nullable()
      .references(Categories, #id, onDelete: KeyAction.cascade)();
  DateTimeColumn get dateCreated =>
      dateTime().withDefault(currentDateAndTime)();
}

@DataClassName("Unit")
class Units extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  IntColumn get amount => integer()();
  DateTimeColumn get dateCreated =>
      dateTime().withDefault(currentDateAndTime)();
}

@DataClassName("Product")
class Products extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get categoryId => integer()
      .nullable()
      .references(Categories, #id, onDelete: KeyAction.cascade)();
  IntColumn get unitId => integer()
      .nullable()
      .references(Units, #id, onDelete: KeyAction.cascade)();
  TextColumn get name => text()();
  TextColumn get remarks => text().nullable()();
  BoolColumn get isFavorite => boolean().withDefault(const Constant(false))();
  DateTimeColumn get dateCreated =>
      dateTime().withDefault(currentDateAndTime)();
}
```

DAOs & Custom Class
```dart
@DriftAccessor(tables: [Categories])
class CategoriesDao extends DatabaseAccessor<AppDatabase>
    with _$CategoriesDaoMixin {
CategoriesDao(AppDatabase db) : super(db);
@override
  Future<int> make(CategoriesCompanion category) async {
    return await into(categories).insert(category);
  }
}

@DriftAccessor(tables: [Units])
class UnitsDao extends DatabaseAccessor<AppDatabase>
    with _$UnitsDaoMixin {
UnitsDao(AppDatabase db) : super(db);
@override
  Future<int> make(UnitsCompanion unit) async {
    return await into(units).insert(unit);
  }
}

class ProductWithDetails {
  ProductWithDetails({
    required this.id,
    required this.name,
    required this.remarks,
    required this.isFavorite,
    required this.category,
    required this.unit,
  });

  final int id;
  final String name;
  final String remarks;
  final bool isFavorite;

  final String category;
  final String unit;
}

@DriftAccessor(tables: [Products])
class ProductsDao extends DatabaseAccessor<AppDatabase>
    with _$ProductsDaoMixin {
  ProductsDao(AppDatabase db) : super(db);

  // Custom query
  Stream<List<ProductWithDetails>> watchProducts() {
    var _query = select(products).join([
      leftOuterJoin(
        categories,
        categories.id.equalsExp(products.categoryId),
        useColumns: false,
      ),
      leftOuterJoin(
        units,
        units.id.equalsExp(products.unitId),
        useColumns: false,
      ),
    ]);

   // This method returns nothing ?? 
   // Even if database has entries
   // Made via sqlite insert or ui button press
    return _query.watch().map((rows) {
      return rows.map((row) {
        final _product = row.readTable(products);
        final _category = row.read(categories.name);
        final _unit = row.read(units.name);

        return ProductWithDetails(
          id: _product.id,
          name: _product.name,
          remarks: _product.remarks!,
          isFavorite: _product.isFavorite,
          category: _category!,
          unit: _unit!,
        );
      }).toList();
    });
  }
}
```

### UI
```dart
class ProductIndex extends StatefulWidget {
  const ProductIndex({Key? key}) : super(key: key);

  @override
  State<ProductIndex> createState() => _ProductIndexState();
}

class _ProductIndexState extends State<ProductIndex> {
  @override
  Widget build(BuildContext context) {
    final _db = context.read<AppDatabase>();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Product Index'),
      ),
      body: StreamBuilder<List<ProductWithDetails>>(
        stream: _db.productsDao.watchProducts(),
        builder: (context, snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.none:
            case ConnectionState.waiting:
              return const Center(child: CircularProgressIndicator());
            case ConnectionState.active:
            case ConnectionState.done:
              if (snapshot.hasData && snapshot.data!.isNotEmpty) {
                List<ProductWithDetails> _products = snapshot.data!;

                return ListView.separated(
                  separatorBuilder: (context, index) => const Divider(),
                  itemBuilder: (context, index) {
                    final _product = _products[index];

                    return ListTile(
                      title: Text(_product.name),
                    );
                  },
                  itemCount: _products.length,
                );
              }

              String _text = '';
              if (snapshot.hasError) {
                _text = 'An error occured please try again later.';
              }
              if (snapshot.data == null || snapshot.data!.isEmpty) {
                _text = 'No available data.';
              }
              return Center(child: Text(_text));
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          // Create Sample data

          // Insert to Category
          final catId = await _db.categoriesDao.make(const CategoriesCompanion(
            name: Value('Test Category 1'),
          ));

          // Insert to Unit
          final unitId = await _db.unitsDao.make(const UnitsCompanion(
            name: Value('Test Unit 1'),
            amount: Value(111),
          ));

          // Insert to Product
          await _db.productsDao.make(ProductsCompanion(
            categoryId: Value(catId),
            unitId: Value(unitId),
            name: const Value('Test Product 1'),
            isFavorite: const Value(true),
          ));
        },
        tooltip: 'Add data',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by simolus3** [comment]
It's not that the stream doesn't update. It actually emits an error, which you're not handling in your `StreamBuilder` :)

```
Invalid argument(s): Invalid call to read(): Instance of 'GeneratedColumn<String?>'. This result set does not have a column for that expression.
#0      TypedResult.read (package:drift/src/runtime/query_builder/statements/select/select.dart:191:5)
#1      ProductsDao.watchProducts.<anonymous closure>.<anonymous closure> (file:///home/simon/drift/drift/example/test.dart:111:31)
```

You can fix this by adding the columns to your query:

```dart
_query.addColumns([categories.name, units.name]);
```

When that is fixed, the query fails with another error:

```
Unhandled exception:
Null check operator used on a null value
#0      ProductsDao.watchProducts.<anonymous closure>.<anonymous closure> (file:///home/simon/drift/drift/example/test.dart:118:36)
```

This time, it's about the null check operator in `_product.remarks!`, because you're inserting a product that doesn't have any remarks. Fixing that also fixes the query stream for me, so it looks like drift is behaving as intended here (errors in your `map` callback get emitted as errors through the stream).
