### ISSUE TITLE
no such table error flutter

### ISSUE THREAD

**Issue by beproductivedevelop34** [simolus3/drift#1910]
```
E/Dart    ( 4114): Invalid UTF8 sequence encountered, 
E/Dart    ( 4114): (Error Code: FD + idx: 234 )
E/Dart    ( 4114): (Error Code: 64 + idx: 235 )
E/Dart    ( 4114): (Error Code: 22 + idx: 236 )
E/Dart    ( 4114): (Error Code: 20 + idx: 237 )
E/Dart    ( 4114): (Error Code: 3A + idx: 238 )
E/Dart    ( 4114): (Error Code: 20 + idx: 239 )
E/Dart    ( 4114): (Error Code: 69 + idx: 240 )
E/Dart    ( 4114): (Error Code: 64 + idx: 241 )
E/Dart    ( 4114): (Error Code: 2C + idx: 242 )
E/Dart    ( 4114): (Error Code: D + idx: 243 )
E/Dart    ( 4114): 
E/Dart    ( 4114): Invalid UTF8 sequence encountered, 
E/Dart    ( 4114): (Error Code: FD + idx: 234 )
E/Dart    ( 4114): (Error Code: 64 + idx: 235 )
E/Dart    ( 4114): (Error Code: 22 + idx: 236 )
E/Dart    ( 4114): (Error Code: 20 + idx: 237 )
E/Dart    ( 4114): (Error Code: 3A + idx: 238 )
E/Dart    ( 4114): (Error Code: 20 + idx: 239 )
E/Dart    ( 4114): (Error Code: 69 + idx: 240 )
E/Dart    ( 4114): (Error Code: 64 + idx: 241 )
E/Dart    ( 4114): (Error Code: 2C + idx: 242 )
E/Dart    ( 4114): (Error Code: D + idx: 243 )
E/Dart    ( 4114): 
Restarted application in 1.887ms.
E/SQLiteLog( 4114): (1) no such table: personTablo
E/flutter ( 4114): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: DatabaseException(no such table: personTablo (code 1): , while compiling: SELECT * FROM personTablo) sql 'SELECT * FROM personTablo' args []
E/flutter ( 4114): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter ( 4114): <asynchronous suspension>
E/flutter ( 4114): #1      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:404:30)
E/flutter ( 4114): <asynchronous suspension>
E/flutter ( 4114): #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter ( 4114): <asynchronous suspension>
E/flutter ( 4114): #3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:344:14)
E/flutter ( 4114): <asynchronous suspension>
E/flutter ( 4114): #4      KisilerO.readData (package:database/KisilerO.dart:15:37)
E/flutter ( 4114): <asynchronous suspension>
E/flutter ( 4114): #5      _MyHomePageState.writedData (package:database/main.dart:37:26)
E/flutter ( 4114): <asynchronous suspension>
E/flutter ( 4114): 
```

**Comment by simolus3** [comment]
Did you add this table after your app was already installed? If so, you need to write a [migration](https://drift.simonbinder.eu/docs/advanced-features/migrations/) for it.
During development (if no version has shipped to users yet), you can also just delete your app's data. This should make drift initialize a new database with all the tables on the next run.

I assume this problem was caused by the lack of a migration. If you did write a migration or if the table was there all the time, please let me know and I'll re-open the issue. A good way to check for derivations in the schema is to use [verification at runtime](https://drift.simonbinder.eu/docs/advanced-features/migrations/#verifying-a-database-schema-at-runtime) on debug builds. If this still happens for you, can you enable that and see if it finds anything?

**Comment by beproductivedevelop34** [comment]
I don't like sqflite, I don't want to use it
